# Generated by Django 4.0.4 on 2024-03-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='monet',
            new_name='money',
        ),
    ]
