# Generated by Django 4.0.4 on 2024-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_monet_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='Шановний Пан', max_length=50, verbose_name='професія'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, default=0, verbose_name='Респани'),
        ),
    ]
